version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  sensor_reader:
    privileged: true
    build: .
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources"
      - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
    depends_on:
      - prometheus
      - sensor_reader
